/* -*- c++ -*- */
/*
 * Copyright 2004 Free Software Foundation, Inc.
 * 
 * This file is part of GNU Radio
 * 
 * GNU Radio is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3, or (at your option)
 * any later version.
 * 
 * GNU Radio is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with GNU Radio; see the file COPYING.  If not, write to
 * the Free Software Foundation, Inc., 51 Franklin Street,
 * Boston, MA 02110-1301, USA.
 */

/*
 * config.h is generated by configure.  It contains the results
 * of probing for features, options etc.  It should be the first
 * file included in your .cc file.
 */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <stdio.h>
#include <gnuradio/io_signature.h>
#include "diff_phasor_vcc_impl.h"

namespace gr {
  namespace dab {

diff_phasor_vcc::sptr
diff_phasor_vcc::make(unsigned int length)
{
  return gnuradio::get_initial_sptr
    (new diff_phasor_vcc_impl(length));
}

diff_phasor_vcc_impl::diff_phasor_vcc_impl(unsigned int length)
  : gr::sync_block("diff_phasor_vcc",
             gr::io_signature::make (1, 1, sizeof(gr_complex)*length),
             gr::io_signature::make (1, 1, sizeof(gr_complex)*length)),
  d_length(length)
{
  set_history(2);
  set_tag_propagation_policy(TPP_DONT);
  d_add_item_tag_at = -1;
}


int 
diff_phasor_vcc_impl::work(int noutput_items,
                        gr_vector_const_void_star &input_items,
                        gr_vector_void_star &output_items)
{
  gr_complex const *in = (const gr_complex *) input_items[0];
  gr_complex *out = (gr_complex *) output_items[0];

  std::vector<int> tag_positions;
  int next_tag_position = -1;
  int next_tag_position_index = -1;

  if (d_add_item_tag_at >= 0) {
      if (d_add_item_tag_at < noutput_items) {
          add_item_tag(0, nitems_written(0) + d_add_item_tag_at, pmt::intern("first"), pmt::intern(""), pmt::intern("diff_phasor"));
          d_add_item_tag_at = -1;
      }
      else {
          d_add_item_tag_at = d_add_item_tag_at - noutput_items;
      }
  }

  std::vector<tag_t> tags;
  get_tags_in_range(tags, 0, nitems_read(0), nitems_read(0) + noutput_items, pmt::mp("first"));
  for(int i=0;i<tags.size();i++) {
      int current;
      current = tags[i].offset - nitems_read(0);
      tag_positions.push_back(current);
      next_tag_position_index = 0;
  }
  if(next_tag_position_index >= 0) {
      next_tag_position = tag_positions[next_tag_position_index];
  }

  for(unsigned int i = 0; i < noutput_items*d_length; i++){

    if (next_tag_position == i) { /* there was a trigger signal d_num_symbols-1 symbols before -> update equalizer */
      if ((i + 2-1) < noutput_items)
          add_item_tag(0, nitems_written(0) + i+2-1, pmt::intern("first"), pmt::intern(""), pmt::intern("diff_phasor"));
      else {
          d_add_item_tag_at = (i + 2-1) - noutput_items;
      }

      next_tag_position_index++;
      if (next_tag_position_index == tag_positions.size()) {
        next_tag_position_index = -1;
        next_tag_position = -1;
      }
      else {
        next_tag_position = tag_positions[next_tag_position_index];
      }
    }

    out[i] = in[i+d_length] * conj(in[i]);
  }
    
  return noutput_items;
}

}
}
