# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_frontend.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(904, 716)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.mode_tabs = QtGui.QTabWidget(self.centralwidget)
        self.mode_tabs.setEnabled(True)
        self.mode_tabs.setObjectName(_fromUtf8("mode_tabs"))
        self.tab_reception = QtGui.QWidget()
        self.tab_reception.setObjectName(_fromUtf8("tab_reception"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_reception)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.label_21 = QtGui.QLabel(self.tab_reception)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_6.addWidget(self.label_21)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbtn_USRP = QtGui.QRadioButton(self.tab_reception)
        self.rbtn_USRP.setChecked(True)
        self.rbtn_USRP.setAutoRepeat(False)
        self.rbtn_USRP.setObjectName(_fromUtf8("rbtn_USRP"))
        self.horizontalLayout.addWidget(self.rbtn_USRP)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_frequency = QtGui.QLabel(self.tab_reception)
        self.label_frequency.setObjectName(_fromUtf8("label_frequency"))
        self.horizontalLayout.addWidget(self.label_frequency)
        self.spinbox_frequency = QtGui.QSpinBox(self.tab_reception)
        self.spinbox_frequency.setMaximum(1000000000)
        self.spinbox_frequency.setProperty("value", 208064000)
        self.spinbox_frequency.setObjectName(_fromUtf8("spinbox_frequency"))
        self.horizontalLayout.addWidget(self.spinbox_frequency)
        self.label_4 = QtGui.QLabel(self.tab_reception)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rbtn_File = QtGui.QRadioButton(self.tab_reception)
        self.rbtn_File.setObjectName(_fromUtf8("rbtn_File"))
        self.horizontalLayout_6.addWidget(self.rbtn_File)
        self.label_path = QtGui.QLabel(self.tab_reception)
        self.label_path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        self.label_path.setMinimumSize(QtCore.QSize(100, 0))
        self.label_path.setFrameShape(QtGui.QFrame.Box)
        self.label_path.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_path.setObjectName(_fromUtf8("label_path"))
        self.horizontalLayout_6.addWidget(self.label_path)
        self.btn_file_path = QtGui.QToolButton(self.tab_reception)
        self.btn_file_path.setEnabled(False)
        self.btn_file_path.setObjectName(_fromUtf8("btn_file_path"))
        self.horizontalLayout_6.addWidget(self.btn_file_path)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.btn_init = QtGui.QPushButton(self.tab_reception)
        font = QtGui.QFont()
        font.setKerning(True)
        self.btn_init.setFont(font)
        self.btn_init.setCheckable(False)
        self.btn_init.setObjectName(_fromUtf8("btn_init"))
        self.verticalLayout_6.addWidget(self.btn_init)
        self.table_mci = QtGui.QTableWidget(self.tab_reception)
        self.table_mci.setObjectName(_fromUtf8("table_mci"))
        self.table_mci.setColumnCount(3)
        self.table_mci.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(2, item)
        self.verticalLayout_6.addWidget(self.table_mci)
        self.btn_update_info = QtGui.QPushButton(self.tab_reception)
        self.btn_update_info.setObjectName(_fromUtf8("btn_update_info"))
        self.verticalLayout_6.addWidget(self.btn_update_info)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.btn_debug = QtGui.QPushButton(self.tab_reception)
        self.btn_debug.setObjectName(_fromUtf8("btn_debug"))
        self.verticalLayout_6.addWidget(self.btn_debug)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.line = QtGui.QFrame(self.tab_reception)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.txt_info = QtGui.QPlainTextEdit(self.tab_reception)
        self.txt_info.setObjectName(_fromUtf8("txt_info"))
        self.verticalLayout_7.addWidget(self.txt_info)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem2)
        self.label_2 = QtGui.QLabel(self.tab_reception)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_play = QtGui.QPushButton(self.tab_reception)
        self.btn_play.setEnabled(False)
        self.btn_play.setObjectName(_fromUtf8("btn_play"))
        self.horizontalLayout_5.addWidget(self.btn_play)
        self.btn_stop = QtGui.QPushButton(self.tab_reception)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.horizontalLayout_5.addWidget(self.btn_stop)
        self.btn_record = QtGui.QPushButton(self.tab_reception)
        self.btn_record.setEnabled(False)
        self.btn_record.setObjectName(_fromUtf8("btn_record"))
        self.horizontalLayout_5.addWidget(self.btn_record)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tab_reception)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.slider_volume = QtGui.QSlider(self.tab_reception)
        self.slider_volume.setEnabled(False)
        self.slider_volume.setMaximum(100)
        self.slider_volume.setProperty("value", 80)
        self.slider_volume.setSliderPosition(80)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName(_fromUtf8("slider_volume"))
        self.horizontalLayout_4.addWidget(self.slider_volume)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.mode_tabs.addTab(self.tab_reception, _fromUtf8(""))
        self.tab_transmission = QtGui.QWidget()
        self.tab_transmission.setObjectName(_fromUtf8("tab_transmission"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_transmission)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.t_label_choose_sink = QtGui.QLabel(self.tab_transmission)
        self.t_label_choose_sink.setObjectName(_fromUtf8("t_label_choose_sink"))
        self.verticalLayout_5.addWidget(self.t_label_choose_sink)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.t_rbtn_USRP = QtGui.QRadioButton(self.tab_transmission)
        self.t_rbtn_USRP.setEnabled(True)
        self.t_rbtn_USRP.setChecked(True)
        self.t_rbtn_USRP.setObjectName(_fromUtf8("t_rbtn_USRP"))
        self.horizontalLayout_9.addWidget(self.t_rbtn_USRP)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem3)
        self.t_label_frequency = QtGui.QLabel(self.tab_transmission)
        self.t_label_frequency.setObjectName(_fromUtf8("t_label_frequency"))
        self.horizontalLayout_9.addWidget(self.t_label_frequency)
        self.t_spinbox_frequency = QtGui.QSpinBox(self.tab_transmission)
        self.t_spinbox_frequency.setMaximum(1000000000)
        self.t_spinbox_frequency.setProperty("value", 208064000)
        self.t_spinbox_frequency.setObjectName(_fromUtf8("t_spinbox_frequency"))
        self.horizontalLayout_9.addWidget(self.t_spinbox_frequency)
        self.label = QtGui.QLabel(self.tab_transmission)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.t_rbtn_File = QtGui.QRadioButton(self.tab_transmission)
        self.t_rbtn_File.setObjectName(_fromUtf8("t_rbtn_File"))
        self.horizontalLayout_10.addWidget(self.t_rbtn_File)
        self.t_label_sink = QtGui.QLabel(self.tab_transmission)
        self.t_label_sink.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_sink.sizePolicy().hasHeightForWidth())
        self.t_label_sink.setSizePolicy(sizePolicy)
        self.t_label_sink.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_sink.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.t_label_sink.setFrameShape(QtGui.QFrame.Box)
        self.t_label_sink.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_sink.setObjectName(_fromUtf8("t_label_sink"))
        self.horizontalLayout_10.addWidget(self.t_label_sink)
        self.t_btn_file_path = QtGui.QToolButton(self.tab_transmission)
        self.t_btn_file_path.setEnabled(False)
        self.t_btn_file_path.setObjectName(_fromUtf8("t_btn_file_path"))
        self.horizontalLayout_10.addWidget(self.t_btn_file_path)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.line_4 = QtGui.QFrame(self.tab_transmission)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_5.addWidget(self.line_4)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_12 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.tab_transmission)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.t_edit_ensemble_label = QtGui.QLineEdit(self.tab_transmission)
        self.t_edit_ensemble_label.setObjectName(_fromUtf8("t_edit_ensemble_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.t_edit_ensemble_label)
        self.label_14 = QtGui.QLabel(self.tab_transmission)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.tab_transmission)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.t_edit_service_label = QtGui.QLineEdit(self.tab_transmission)
        self.t_edit_service_label.setObjectName(_fromUtf8("t_edit_service_label"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.t_edit_service_label)
        self.label_17 = QtGui.QLabel(self.tab_transmission)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_17)
        self.t_spin_num_subch = QtGui.QSpinBox(self.tab_transmission)
        self.t_spin_num_subch.setMaximum(7)
        self.t_spin_num_subch.setProperty("value", 1)
        self.t_spin_num_subch.setObjectName(_fromUtf8("t_spin_num_subch"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.t_spin_num_subch)
        self.label_23 = QtGui.QLabel(self.tab_transmission)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_23)
        self.t_spin_countryID = QtGui.QSpinBox(self.tab_transmission)
        self.t_spin_countryID.setObjectName(_fromUtf8("t_spin_countryID"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.t_spin_countryID)
        self.t_combo_language = QtGui.QComboBox(self.tab_transmission)
        self.t_combo_language.setObjectName(_fromUtf8("t_combo_language"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.t_combo_language)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        spacerItem4 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem4)
        self.t_btn_init = QtGui.QPushButton(self.tab_transmission)
        self.t_btn_init.setObjectName(_fromUtf8("t_btn_init"))
        self.verticalLayout_5.addWidget(self.t_btn_init)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.line_3 = QtGui.QFrame(self.tab_transmission)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_7.addWidget(self.line_3)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.scrollArea = QtGui.QScrollArea(self.tab_transmission)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -443, 403, 922))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.line_2)
        self.t_label_comp2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp2.setFont(font)
        self.t_label_comp2.setObjectName(_fromUtf8("t_label_comp2"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.t_label_comp2)
        self.t_label_rate2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate2.setObjectName(_fromUtf8("t_label_rate2"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.t_label_rate2)
        self.t_spin_rate2 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate2.setMaximum(999)
        self.t_spin_rate2.setObjectName(_fromUtf8("t_spin_rate2"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.t_spin_rate2)
        self.t_label_prot2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot2.setObjectName(_fromUtf8("t_label_prot2"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.t_label_prot2)
        self.t_spin_prot2 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot2.setObjectName(_fromUtf8("t_spin_prot2"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.t_spin_prot2)
        self.t_label_comp_src2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src2.setObjectName(_fromUtf8("t_label_comp_src2"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.t_label_comp_src2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.t_label_path_src2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src2.sizePolicy().hasHeightForWidth())
        self.t_label_path_src2.setSizePolicy(sizePolicy)
        self.t_label_path_src2.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src2.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src2.setObjectName(_fromUtf8("t_label_path_src2"))
        self.horizontalLayout_14.addWidget(self.t_label_path_src2)
        self.t_btn_path_src2 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src2.setObjectName(_fromUtf8("t_btn_path_src2"))
        self.horizontalLayout_14.addWidget(self.t_btn_path_src2)
        self.formLayout_3.setLayout(9, QtGui.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.t_label_comp3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp3.setFont(font)
        self.t_label_comp3.setObjectName(_fromUtf8("t_label_comp3"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.t_label_comp3)
        self.t_label_rate3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate3.setObjectName(_fromUtf8("t_label_rate3"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.LabelRole, self.t_label_rate3)
        self.t_spin_rate3 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate3.setMaximum(999)
        self.t_spin_rate3.setObjectName(_fromUtf8("t_spin_rate3"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.FieldRole, self.t_spin_rate3)
        self.t_label_prot3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot3.setObjectName(_fromUtf8("t_label_prot3"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.LabelRole, self.t_label_prot3)
        self.t_spin_prot3 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot3.setObjectName(_fromUtf8("t_spin_prot3"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.FieldRole, self.t_spin_prot3)
        self.t_label_comp_src3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src3.setObjectName(_fromUtf8("t_label_comp_src3"))
        self.formLayout_3.setWidget(13, QtGui.QFormLayout.LabelRole, self.t_label_comp_src3)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.t_label_path_src3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src3.sizePolicy().hasHeightForWidth())
        self.t_label_path_src3.setSizePolicy(sizePolicy)
        self.t_label_path_src3.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src3.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src3.setObjectName(_fromUtf8("t_label_path_src3"))
        self.horizontalLayout_15.addWidget(self.t_label_path_src3)
        self.t_btn_path_src3 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src3.setObjectName(_fromUtf8("t_btn_path_src3"))
        self.horizontalLayout_15.addWidget(self.t_btn_path_src3)
        self.formLayout_3.setLayout(13, QtGui.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.t_label_comp4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp4.setFont(font)
        self.t_label_comp4.setObjectName(_fromUtf8("t_label_comp4"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.LabelRole, self.t_label_comp4)
        self.t_label_rate4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate4.setObjectName(_fromUtf8("t_label_rate4"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.LabelRole, self.t_label_rate4)
        self.t_spin_rate4 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate4.setMaximum(999)
        self.t_spin_rate4.setObjectName(_fromUtf8("t_spin_rate4"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.FieldRole, self.t_spin_rate4)
        self.t_label_prot4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot4.setObjectName(_fromUtf8("t_label_prot4"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.LabelRole, self.t_label_prot4)
        self.t_spin_prot4 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot4.setObjectName(_fromUtf8("t_spin_prot4"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.FieldRole, self.t_spin_prot4)
        self.t_label_comp_src4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src4.setObjectName(_fromUtf8("t_label_comp_src4"))
        self.formLayout_3.setWidget(17, QtGui.QFormLayout.LabelRole, self.t_label_comp_src4)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.t_label_path_src4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src4.sizePolicy().hasHeightForWidth())
        self.t_label_path_src4.setSizePolicy(sizePolicy)
        self.t_label_path_src4.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src4.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src4.setObjectName(_fromUtf8("t_label_path_src4"))
        self.horizontalLayout_16.addWidget(self.t_label_path_src4)
        self.t_btn_path_src4 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src4.setObjectName(_fromUtf8("t_btn_path_src4"))
        self.horizontalLayout_16.addWidget(self.t_btn_path_src4)
        self.formLayout_3.setLayout(17, QtGui.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.t_label_comp5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp5.setFont(font)
        self.t_label_comp5.setObjectName(_fromUtf8("t_label_comp5"))
        self.formLayout_3.setWidget(18, QtGui.QFormLayout.LabelRole, self.t_label_comp5)
        self.t_label_rate5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate5.setObjectName(_fromUtf8("t_label_rate5"))
        self.formLayout_3.setWidget(19, QtGui.QFormLayout.LabelRole, self.t_label_rate5)
        self.t_spin_rate5 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate5.setMaximum(999)
        self.t_spin_rate5.setObjectName(_fromUtf8("t_spin_rate5"))
        self.formLayout_3.setWidget(19, QtGui.QFormLayout.FieldRole, self.t_spin_rate5)
        self.t_label_prot5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot5.setObjectName(_fromUtf8("t_label_prot5"))
        self.formLayout_3.setWidget(20, QtGui.QFormLayout.LabelRole, self.t_label_prot5)
        self.t_spin_prot5 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot5.setObjectName(_fromUtf8("t_spin_prot5"))
        self.formLayout_3.setWidget(20, QtGui.QFormLayout.FieldRole, self.t_spin_prot5)
        self.t_label_comp_src5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src5.setObjectName(_fromUtf8("t_label_comp_src5"))
        self.formLayout_3.setWidget(21, QtGui.QFormLayout.LabelRole, self.t_label_comp_src5)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.t_label_path_src5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src5.sizePolicy().hasHeightForWidth())
        self.t_label_path_src5.setSizePolicy(sizePolicy)
        self.t_label_path_src5.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src5.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src5.setObjectName(_fromUtf8("t_label_path_src5"))
        self.horizontalLayout_17.addWidget(self.t_label_path_src5)
        self.t_btn_path_src5 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src5.setObjectName(_fromUtf8("t_btn_path_src5"))
        self.horizontalLayout_17.addWidget(self.t_btn_path_src5)
        self.formLayout_3.setLayout(21, QtGui.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.t_label_comp6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp6.setFont(font)
        self.t_label_comp6.setObjectName(_fromUtf8("t_label_comp6"))
        self.formLayout_3.setWidget(22, QtGui.QFormLayout.LabelRole, self.t_label_comp6)
        self.t_label_rate6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate6.setObjectName(_fromUtf8("t_label_rate6"))
        self.formLayout_3.setWidget(23, QtGui.QFormLayout.LabelRole, self.t_label_rate6)
        self.t_spin_rate6 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate6.setMaximum(999)
        self.t_spin_rate6.setObjectName(_fromUtf8("t_spin_rate6"))
        self.formLayout_3.setWidget(23, QtGui.QFormLayout.FieldRole, self.t_spin_rate6)
        self.t_label_prot6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot6.setObjectName(_fromUtf8("t_label_prot6"))
        self.formLayout_3.setWidget(24, QtGui.QFormLayout.LabelRole, self.t_label_prot6)
        self.t_spin_prot6 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot6.setObjectName(_fromUtf8("t_spin_prot6"))
        self.formLayout_3.setWidget(24, QtGui.QFormLayout.FieldRole, self.t_spin_prot6)
        self.t_label_comp_src6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src6.setObjectName(_fromUtf8("t_label_comp_src6"))
        self.formLayout_3.setWidget(25, QtGui.QFormLayout.LabelRole, self.t_label_comp_src6)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.t_label_path_src6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src6.sizePolicy().hasHeightForWidth())
        self.t_label_path_src6.setSizePolicy(sizePolicy)
        self.t_label_path_src6.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src6.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src6.setObjectName(_fromUtf8("t_label_path_src6"))
        self.horizontalLayout_18.addWidget(self.t_label_path_src6)
        self.t_btn_path_src6 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src6.setObjectName(_fromUtf8("t_btn_path_src6"))
        self.horizontalLayout_18.addWidget(self.t_btn_path_src6)
        self.formLayout_3.setLayout(25, QtGui.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.t_label_comp7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp7.setFont(font)
        self.t_label_comp7.setObjectName(_fromUtf8("t_label_comp7"))
        self.formLayout_3.setWidget(26, QtGui.QFormLayout.LabelRole, self.t_label_comp7)
        self.t_label_rate7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate7.setObjectName(_fromUtf8("t_label_rate7"))
        self.formLayout_3.setWidget(27, QtGui.QFormLayout.LabelRole, self.t_label_rate7)
        self.t_spin_rate7 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate7.setMaximum(999)
        self.t_spin_rate7.setObjectName(_fromUtf8("t_spin_rate7"))
        self.formLayout_3.setWidget(27, QtGui.QFormLayout.FieldRole, self.t_spin_rate7)
        self.t_label_prot7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot7.setObjectName(_fromUtf8("t_label_prot7"))
        self.formLayout_3.setWidget(28, QtGui.QFormLayout.LabelRole, self.t_label_prot7)
        self.t_spin_prot7 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot7.setEnabled(True)
        self.t_spin_prot7.setObjectName(_fromUtf8("t_spin_prot7"))
        self.formLayout_3.setWidget(28, QtGui.QFormLayout.FieldRole, self.t_spin_prot7)
        self.t_label_comp_src7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src7.setObjectName(_fromUtf8("t_label_comp_src7"))
        self.formLayout_3.setWidget(29, QtGui.QFormLayout.LabelRole, self.t_label_comp_src7)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.t_label_path_src7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src7.sizePolicy().hasHeightForWidth())
        self.t_label_path_src7.setSizePolicy(sizePolicy)
        self.t_label_path_src7.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src7.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src7.setObjectName(_fromUtf8("t_label_path_src7"))
        self.horizontalLayout_19.addWidget(self.t_label_path_src7)
        self.t_btn_path_src7 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src7.setObjectName(_fromUtf8("t_btn_path_src7"))
        self.horizontalLayout_19.addWidget(self.t_btn_path_src7)
        self.formLayout_3.setLayout(29, QtGui.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.t_label_path_src1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src1.sizePolicy().hasHeightForWidth())
        self.t_label_path_src1.setSizePolicy(sizePolicy)
        self.t_label_path_src1.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.t_label_path_src1.setFont(font)
        self.t_label_path_src1.setAutoFillBackground(False)
        self.t_label_path_src1.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src1.setObjectName(_fromUtf8("t_label_path_src1"))
        self.horizontalLayout_13.addWidget(self.t_label_path_src1)
        self.t_btn_path_src1 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src1.setObjectName(_fromUtf8("t_btn_path_src1"))
        self.horizontalLayout_13.addWidget(self.t_btn_path_src1)
        self.formLayout_3.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.t_label_comp_src1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src1.setObjectName(_fromUtf8("t_label_comp_src1"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.t_label_comp_src1)
        self.t_label_prot1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot1.setObjectName(_fromUtf8("t_label_prot1"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.t_label_prot1)
        self.t_spin_rate1 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate1.setMaximum(999)
        self.t_spin_rate1.setProperty("value", 112)
        self.t_spin_rate1.setObjectName(_fromUtf8("t_spin_rate1"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.t_spin_rate1)
        self.t_label_rate1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate1.setObjectName(_fromUtf8("t_label_rate1"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.t_label_rate1)
        self.t_label_comp1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp1.setFont(font)
        self.t_label_comp1.setObjectName(_fromUtf8("t_label_comp1"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.t_label_comp1)
        self.t_spin_prot1 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot1.setMaximum(3)
        self.t_spin_prot1.setProperty("value", 2)
        self.t_spin_prot1.setObjectName(_fromUtf8("t_spin_prot1"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.t_spin_prot1)
        self.t_label_heading_service_comp = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_heading_service_comp.setFont(font)
        self.t_label_heading_service_comp.setObjectName(_fromUtf8("t_label_heading_service_comp"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.t_label_heading_service_comp)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_8.addWidget(self.scrollArea)
        self.line_5 = QtGui.QFrame(self.tab_transmission)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_8.addWidget(self.line_5)
        self.label_20 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_8.addWidget(self.label_20)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_18 = QtGui.QLabel(self.tab_transmission)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_20.addWidget(self.label_18)
        self.spinBox = QtGui.QSpinBox(self.tab_transmission)
        self.spinBox.setObjectName(_fromUtf8("spinBox"))
        self.horizontalLayout_20.addWidget(self.spinBox)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.t_btn_play = QtGui.QPushButton(self.tab_transmission)
        self.t_btn_play.setObjectName(_fromUtf8("t_btn_play"))
        self.horizontalLayout_11.addWidget(self.t_btn_play)
        self.t_btn_stop = QtGui.QPushButton(self.tab_transmission)
        self.t_btn_stop.setObjectName(_fromUtf8("t_btn_stop"))
        self.horizontalLayout_11.addWidget(self.t_btn_stop)
        self.t_btn_record = QtGui.QPushButton(self.tab_transmission)
        self.t_btn_record.setObjectName(_fromUtf8("t_btn_record"))
        self.horizontalLayout_11.addWidget(self.t_btn_record)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_19 = QtGui.QLabel(self.tab_transmission)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_12.addWidget(self.label_19)
        self.t_slider_volume = QtGui.QSlider(self.tab_transmission)
        self.t_slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.t_slider_volume.setObjectName(_fromUtf8("t_slider_volume"))
        self.horizontalLayout_12.addWidget(self.t_slider_volume)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.mode_tabs.addTab(self.tab_transmission, _fromUtf8(""))
        self.verticalLayout.addWidget(self.mode_tabs)
        self.Heading = QtGui.QLabel(self.centralwidget)
        self.Heading.setObjectName(_fromUtf8("Heading"))
        self.verticalLayout.addWidget(self.Heading)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.mode_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_21.setText(_translate("MainWindow", "Source", None))
        self.rbtn_USRP.setText(_translate("MainWindow", "USRP", None))
        self.label_frequency.setText(_translate("MainWindow", "frequency", None))
        self.label_4.setText(_translate("MainWindow", "Hz ", None))
        self.rbtn_File.setText(_translate("MainWindow", "File", None))
        self.label_path.setText(_translate("MainWindow", "select path", None))
        self.btn_file_path.setText(_translate("MainWindow", "...", None))
        self.btn_init.setText(_translate("MainWindow", "init", None))
        item = self.table_mci.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.table_mci.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Reference", None))
        item = self.table_mci.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type", None))
        self.btn_update_info.setText(_translate("MainWindow", "update", None))
        self.btn_debug.setText(_translate("MainWindow", "DEBUG", None))
        self.label_2.setText(_translate("MainWindow", "Audio Player", None))
        self.btn_play.setText(_translate("MainWindow", "Play", None))
        self.btn_stop.setText(_translate("MainWindow", "Stop", None))
        self.btn_record.setText(_translate("MainWindow", "Record", None))
        self.label_3.setText(_translate("MainWindow", "Volume", None))
        self.mode_tabs.setTabText(self.mode_tabs.indexOf(self.tab_reception), _translate("MainWindow", "Receiver", None))
        self.t_label_choose_sink.setText(_translate("MainWindow", "Sink", None))
        self.t_rbtn_USRP.setText(_translate("MainWindow", "USRP", None))
        self.t_label_frequency.setText(_translate("MainWindow", "frequency", None))
        self.label.setText(_translate("MainWindow", "Hz ", None))
        self.t_rbtn_File.setText(_translate("MainWindow", "File", None))
        self.t_label_sink.setText(_translate("MainWindow", "select path", None))
        self.t_btn_file_path.setText(_translate("MainWindow", "...", None))
        self.label_12.setText(_translate("MainWindow", "Ensemble info", None))
        self.label_13.setText(_translate("MainWindow", "Label", None))
        self.t_edit_ensemble_label.setText(_translate("MainWindow", "Galaxy News", None))
        self.label_14.setText(_translate("MainWindow", "Country", None))
        self.label_15.setText(_translate("MainWindow", "Service", None))
        self.label_16.setText(_translate("MainWindow", "Label", None))
        self.t_edit_service_label.setText(_translate("MainWindow", "Wasteland Radio", None))
        self.label_17.setText(_translate("MainWindow", "Number of channels", None))
        self.label_23.setText(_translate("MainWindow", "Language", None))
        self.t_btn_init.setText(_translate("MainWindow", "init", None))
        self.t_label_comp2.setText(_translate("MainWindow", "Component 2 ", None))
        self.t_label_rate2.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot2.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src2.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src2.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src2.setText(_translate("MainWindow", "...", None))
        self.t_label_comp3.setText(_translate("MainWindow", "Component 3", None))
        self.t_label_rate3.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot3.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src3.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src3.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src3.setText(_translate("MainWindow", "...", None))
        self.t_label_comp4.setText(_translate("MainWindow", "Component 4", None))
        self.t_label_rate4.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot4.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src4.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src4.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src4.setText(_translate("MainWindow", "...", None))
        self.t_label_comp5.setText(_translate("MainWindow", "Component 5", None))
        self.t_label_rate5.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot5.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src5.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src5.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src5.setText(_translate("MainWindow", "...", None))
        self.t_label_comp6.setText(_translate("MainWindow", "Component 6", None))
        self.t_label_rate6.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot6.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src6.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src6.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src6.setText(_translate("MainWindow", "...", None))
        self.t_label_comp7.setText(_translate("MainWindow", "Component 7", None))
        self.t_label_rate7.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot7.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src7.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src7.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src7.setText(_translate("MainWindow", "...", None))
        self.t_label_path_src1.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src1.setText(_translate("MainWindow", "...", None))
        self.t_label_comp_src1.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_prot1.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_rate1.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_comp1.setText(_translate("MainWindow", "Component 1", None))
        self.t_label_heading_service_comp.setText(_translate("MainWindow", "Service Components", None))
        self.label_20.setText(_translate("MainWindow", "Audio Player", None))
        self.label_18.setText(_translate("MainWindow", "Listen to component", None))
        self.t_btn_play.setText(_translate("MainWindow", "Play", None))
        self.t_btn_stop.setText(_translate("MainWindow", "Stop", None))
        self.t_btn_record.setText(_translate("MainWindow", "Record", None))
        self.label_19.setText(_translate("MainWindow", "Volume", None))
        self.mode_tabs.setTabText(self.mode_tabs.indexOf(self.tab_transmission), _translate("MainWindow", "Transmitter", None))
        self.Heading.setText(_translate("MainWindow", "DABstep", None))

