# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_frontend.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(890, 585)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_21.addWidget(self.label_5)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayout_21.addWidget(self.label_6)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_21)
        self.mode_tabs = QtGui.QTabWidget(self.centralwidget)
        self.mode_tabs.setEnabled(True)
        self.mode_tabs.setObjectName(_fromUtf8("mode_tabs"))
        self.tab_reception = QtGui.QWidget()
        self.tab_reception.setObjectName(_fromUtf8("tab_reception"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_reception)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbtn_USRP = QtGui.QRadioButton(self.tab_reception)
        self.rbtn_USRP.setChecked(True)
        self.rbtn_USRP.setAutoRepeat(False)
        self.rbtn_USRP.setObjectName(_fromUtf8("rbtn_USRP"))
        self.horizontalLayout.addWidget(self.rbtn_USRP)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.label_frequency = QtGui.QLabel(self.tab_reception)
        self.label_frequency.setObjectName(_fromUtf8("label_frequency"))
        self.horizontalLayout.addWidget(self.label_frequency)
        self.spinbox_frequency = QtGui.QSpinBox(self.tab_reception)
        self.spinbox_frequency.setMaximum(1000000000)
        self.spinbox_frequency.setProperty("value", 208064000)
        self.spinbox_frequency.setObjectName(_fromUtf8("spinbox_frequency"))
        self.horizontalLayout.addWidget(self.spinbox_frequency)
        self.label_4 = QtGui.QLabel(self.tab_reception)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout.addWidget(self.label_4)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rbtn_File = QtGui.QRadioButton(self.tab_reception)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbtn_File.sizePolicy().hasHeightForWidth())
        self.rbtn_File.setSizePolicy(sizePolicy)
        self.rbtn_File.setObjectName(_fromUtf8("rbtn_File"))
        self.horizontalLayout_6.addWidget(self.rbtn_File)
        self.label_path = QtGui.QLabel(self.tab_reception)
        self.label_path.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_path.sizePolicy().hasHeightForWidth())
        self.label_path.setSizePolicy(sizePolicy)
        self.label_path.setMinimumSize(QtCore.QSize(100, 0))
        self.label_path.setFrameShape(QtGui.QFrame.Box)
        self.label_path.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_path.setObjectName(_fromUtf8("label_path"))
        self.horizontalLayout_6.addWidget(self.label_path)
        self.btn_file_path = QtGui.QToolButton(self.tab_reception)
        self.btn_file_path.setEnabled(False)
        self.btn_file_path.setObjectName(_fromUtf8("btn_file_path"))
        self.horizontalLayout_6.addWidget(self.btn_file_path)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.table_mci = QtGui.QTableWidget(self.tab_reception)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.table_mci.sizePolicy().hasHeightForWidth())
        self.table_mci.setSizePolicy(sizePolicy)
        self.table_mci.setObjectName(_fromUtf8("table_mci"))
        self.table_mci.setColumnCount(4)
        self.table_mci.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(3, item)
        self.table_mci.horizontalHeader().setCascadingSectionResizes(False)
        self.table_mci.horizontalHeader().setDefaultSectionSize(100)
        self.table_mci.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_6.addWidget(self.table_mci)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.line_8 = QtGui.QFrame(self.tab_reception)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.horizontalLayout_2.addWidget(self.line_8)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_ensemble = QtGui.QLabel(self.tab_reception)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_ensemble.sizePolicy().hasHeightForWidth())
        self.label_ensemble.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(17)
        self.label_ensemble.setFont(font)
        self.label_ensemble.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ensemble.setObjectName(_fromUtf8("label_ensemble"))
        self.horizontalLayout_27.addWidget(self.label_ensemble)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        spacerItem3 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_26 = QtGui.QLabel(self.tab_reception)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_28.addWidget(self.label_26)
        self.lcd_number_num_subch = QtGui.QLCDNumber(self.tab_reception)
        self.lcd_number_num_subch.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcd_number_num_subch.sizePolicy().hasHeightForWidth())
        self.lcd_number_num_subch.setSizePolicy(sizePolicy)
        self.lcd_number_num_subch.setNumDigits(2)
        self.lcd_number_num_subch.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_number_num_subch.setObjectName(_fromUtf8("lcd_number_num_subch"))
        self.horizontalLayout_28.addWidget(self.lcd_number_num_subch)
        self.verticalLayout_10.addLayout(self.horizontalLayout_28)
        self.label_country = QtGui.QLabel(self.tab_reception)
        self.label_country.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_country.setObjectName(_fromUtf8("label_country"))
        self.verticalLayout_10.addWidget(self.label_country)
        spacerItem4 = QtGui.QSpacerItem(20, 0, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem4)
        self.horizontalLayout_27.addLayout(self.verticalLayout_10)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.bar_snr = QtGui.QProgressBar(self.tab_reception)
        self.bar_snr.setStyleSheet(_fromUtf8("tfadsf"))
        self.bar_snr.setMinimum(-20)
        self.bar_snr.setMaximum(20)
        self.bar_snr.setProperty("value", -20)
        self.bar_snr.setFormat(_fromUtf8(""))
        self.bar_snr.setObjectName(_fromUtf8("bar_snr"))
        self.horizontalLayout_23.addWidget(self.bar_snr)
        self.label_snr = QtGui.QLabel(self.tab_reception)
        self.label_snr.setObjectName(_fromUtf8("label_snr"))
        self.horizontalLayout_23.addWidget(self.label_snr)
        self.lcd_snr = QtGui.QLCDNumber(self.tab_reception)
        self.lcd_snr.setSmallDecimalPoint(False)
        self.lcd_snr.setNumDigits(4)
        self.lcd_snr.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcd_snr.setObjectName(_fromUtf8("lcd_snr"))
        self.horizontalLayout_23.addWidget(self.lcd_snr)
        self.label_7 = QtGui.QLabel(self.tab_reception)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_23.addWidget(self.label_7)
        self.verticalLayout_7.addLayout(self.horizontalLayout_23)
        self.line_6 = QtGui.QFrame(self.tab_reception)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.verticalLayout_7.addWidget(self.line_6)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_service = QtGui.QLabel(self.tab_reception)
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_service.setFont(font)
        self.label_service.setAlignment(QtCore.Qt.AlignCenter)
        self.label_service.setObjectName(_fromUtf8("label_service"))
        self.horizontalLayout_24.addWidget(self.label_service)
        self.verticalLayout_7.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_dabplus = QtGui.QLabel(self.tab_reception)
        self.label_dabplus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_dabplus.setObjectName(_fromUtf8("label_dabplus"))
        self.horizontalLayout_25.addWidget(self.label_dabplus)
        self.label_bit_rate = QtGui.QLabel(self.tab_reception)
        self.label_bit_rate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_bit_rate.setObjectName(_fromUtf8("label_bit_rate"))
        self.horizontalLayout_25.addWidget(self.label_bit_rate)
        self.label_primary = QtGui.QLabel(self.tab_reception)
        self.label_primary.setAlignment(QtCore.Qt.AlignCenter)
        self.label_primary.setObjectName(_fromUtf8("label_primary"))
        self.horizontalLayout_25.addWidget(self.label_primary)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.line_7 = QtGui.QFrame(self.tab_reception)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.verticalLayout_7.addWidget(self.line_7)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem5)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.btn_init = QtGui.QPushButton(self.tab_reception)
        font = QtGui.QFont()
        font.setKerning(True)
        self.btn_init.setFont(font)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("network-receive"))
        self.btn_init.setIcon(icon)
        self.btn_init.setCheckable(False)
        self.btn_init.setObjectName(_fromUtf8("btn_init"))
        self.horizontalLayout_26.addWidget(self.btn_init)
        self.btn_update_info = QtGui.QPushButton(self.tab_reception)
        self.btn_update_info.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("system-search"))
        self.btn_update_info.setIcon(icon)
        self.btn_update_info.setObjectName(_fromUtf8("btn_update_info"))
        self.horizontalLayout_26.addWidget(self.btn_update_info)
        self.verticalLayout_7.addLayout(self.horizontalLayout_26)
        self.line_9 = QtGui.QFrame(self.tab_reception)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.verticalLayout_7.addWidget(self.line_9)
        self.label_2 = QtGui.QLabel(self.tab_reception)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_play = QtGui.QPushButton(self.tab_reception)
        self.btn_play.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.btn_play.setIcon(icon)
        self.btn_play.setObjectName(_fromUtf8("btn_play"))
        self.horizontalLayout_5.addWidget(self.btn_play)
        self.btn_stop = QtGui.QPushButton(self.tab_reception)
        self.btn_stop.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-stop"))
        self.btn_stop.setIcon(icon)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.horizontalLayout_5.addWidget(self.btn_stop)
        self.btn_record = QtGui.QPushButton(self.tab_reception)
        self.btn_record.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-record"))
        self.btn_record.setIcon(icon)
        self.btn_record.setObjectName(_fromUtf8("btn_record"))
        self.horizontalLayout_5.addWidget(self.btn_record)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tab_reception)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.slider_volume = QtGui.QSlider(self.tab_reception)
        self.slider_volume.setEnabled(False)
        self.slider_volume.setMaximum(100)
        self.slider_volume.setProperty("value", 80)
        self.slider_volume.setSliderPosition(80)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName(_fromUtf8("slider_volume"))
        self.horizontalLayout_4.addWidget(self.slider_volume)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.mode_tabs.addTab(self.tab_reception, _fromUtf8(""))
        self.tab_transmission = QtGui.QWidget()
        self.tab_transmission.setObjectName(_fromUtf8("tab_transmission"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_transmission)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.t_rbtn_USRP = QtGui.QRadioButton(self.tab_transmission)
        self.t_rbtn_USRP.setEnabled(True)
        self.t_rbtn_USRP.setChecked(True)
        self.t_rbtn_USRP.setObjectName(_fromUtf8("t_rbtn_USRP"))
        self.horizontalLayout_9.addWidget(self.t_rbtn_USRP)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem6)
        self.t_label_frequency = QtGui.QLabel(self.tab_transmission)
        self.t_label_frequency.setObjectName(_fromUtf8("t_label_frequency"))
        self.horizontalLayout_9.addWidget(self.t_label_frequency)
        self.t_spinbox_frequency = QtGui.QSpinBox(self.tab_transmission)
        self.t_spinbox_frequency.setMaximum(1000000000)
        self.t_spinbox_frequency.setProperty("value", 208064000)
        self.t_spinbox_frequency.setObjectName(_fromUtf8("t_spinbox_frequency"))
        self.horizontalLayout_9.addWidget(self.t_spinbox_frequency)
        self.label = QtGui.QLabel(self.tab_transmission)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_9.addWidget(self.label)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.t_rbtn_File = QtGui.QRadioButton(self.tab_transmission)
        self.t_rbtn_File.setObjectName(_fromUtf8("t_rbtn_File"))
        self.horizontalLayout_10.addWidget(self.t_rbtn_File)
        self.t_edit_file_name = QtGui.QLineEdit(self.tab_transmission)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_edit_file_name.sizePolicy().hasHeightForWidth())
        self.t_edit_file_name.setSizePolicy(sizePolicy)
        self.t_edit_file_name.setObjectName(_fromUtf8("t_edit_file_name"))
        self.horizontalLayout_10.addWidget(self.t_edit_file_name)
        self.t_label_sink = QtGui.QLabel(self.tab_transmission)
        self.t_label_sink.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_sink.sizePolicy().hasHeightForWidth())
        self.t_label_sink.setSizePolicy(sizePolicy)
        self.t_label_sink.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_sink.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.t_label_sink.setFrameShape(QtGui.QFrame.Box)
        self.t_label_sink.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_sink.setObjectName(_fromUtf8("t_label_sink"))
        self.horizontalLayout_10.addWidget(self.t_label_sink)
        self.t_btn_file_path = QtGui.QToolButton(self.tab_transmission)
        self.t_btn_file_path.setEnabled(False)
        self.t_btn_file_path.setObjectName(_fromUtf8("t_btn_file_path"))
        self.horizontalLayout_10.addWidget(self.t_btn_file_path)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.line_4 = QtGui.QFrame(self.tab_transmission)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.verticalLayout_5.addWidget(self.line_4)
        self.scrollArea = QtGui.QScrollArea(self.tab_transmission)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, -587, 397, 954))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.line_2 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.line_2)
        self.t_label_heading_service_comp = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_heading_service_comp.setFont(font)
        self.t_label_heading_service_comp.setObjectName(_fromUtf8("t_label_heading_service_comp"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.t_label_heading_service_comp)
        self.t_label_comp1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp1.setFont(font)
        self.t_label_comp1.setObjectName(_fromUtf8("t_label_comp1"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.t_label_comp1)
        self.t_label_rate1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate1.setObjectName(_fromUtf8("t_label_rate1"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.t_label_rate1)
        self.t_spin_rate1 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate1.setMaximum(999)
        self.t_spin_rate1.setProperty("value", 112)
        self.t_spin_rate1.setObjectName(_fromUtf8("t_spin_rate1"))
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.FieldRole, self.t_spin_rate1)
        self.t_label_prot1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot1.setObjectName(_fromUtf8("t_label_prot1"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.LabelRole, self.t_label_prot1)
        self.t_spin_prot1 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot1.setMaximum(3)
        self.t_spin_prot1.setProperty("value", 2)
        self.t_spin_prot1.setObjectName(_fromUtf8("t_spin_prot1"))
        self.formLayout_3.setWidget(4, QtGui.QFormLayout.FieldRole, self.t_spin_prot1)
        self.t_label_comp_src1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src1.setObjectName(_fromUtf8("t_label_comp_src1"))
        self.formLayout_3.setWidget(5, QtGui.QFormLayout.LabelRole, self.t_label_comp_src1)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.t_label_path_src1 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src1.sizePolicy().hasHeightForWidth())
        self.t_label_path_src1.setSizePolicy(sizePolicy)
        self.t_label_path_src1.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setUnderline(False)
        font.setStrikeOut(False)
        self.t_label_path_src1.setFont(font)
        self.t_label_path_src1.setAutoFillBackground(False)
        self.t_label_path_src1.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src1.setObjectName(_fromUtf8("t_label_path_src1"))
        self.horizontalLayout_13.addWidget(self.t_label_path_src1)
        self.t_btn_path_src1 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src1.setObjectName(_fromUtf8("t_btn_path_src1"))
        self.horizontalLayout_13.addWidget(self.t_btn_path_src1)
        self.formLayout_3.setLayout(5, QtGui.QFormLayout.FieldRole, self.horizontalLayout_13)
        self.t_label_comp2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp2.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp2.setFont(font)
        self.t_label_comp2.setObjectName(_fromUtf8("t_label_comp2"))
        self.formLayout_3.setWidget(6, QtGui.QFormLayout.LabelRole, self.t_label_comp2)
        self.t_label_rate2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate2.setObjectName(_fromUtf8("t_label_rate2"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.LabelRole, self.t_label_rate2)
        self.t_spin_rate2 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate2.setMaximum(999)
        self.t_spin_rate2.setProperty("value", 112)
        self.t_spin_rate2.setObjectName(_fromUtf8("t_spin_rate2"))
        self.formLayout_3.setWidget(7, QtGui.QFormLayout.FieldRole, self.t_spin_rate2)
        self.t_label_prot2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot2.setObjectName(_fromUtf8("t_label_prot2"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.LabelRole, self.t_label_prot2)
        self.t_spin_prot2 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot2.setProperty("value", 2)
        self.t_spin_prot2.setObjectName(_fromUtf8("t_spin_prot2"))
        self.formLayout_3.setWidget(8, QtGui.QFormLayout.FieldRole, self.t_spin_prot2)
        self.t_label_comp_src2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src2.setObjectName(_fromUtf8("t_label_comp_src2"))
        self.formLayout_3.setWidget(9, QtGui.QFormLayout.LabelRole, self.t_label_comp_src2)
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.t_label_path_src2 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src2.sizePolicy().hasHeightForWidth())
        self.t_label_path_src2.setSizePolicy(sizePolicy)
        self.t_label_path_src2.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src2.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src2.setObjectName(_fromUtf8("t_label_path_src2"))
        self.horizontalLayout_14.addWidget(self.t_label_path_src2)
        self.t_btn_path_src2 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src2.setObjectName(_fromUtf8("t_btn_path_src2"))
        self.horizontalLayout_14.addWidget(self.t_btn_path_src2)
        self.formLayout_3.setLayout(9, QtGui.QFormLayout.FieldRole, self.horizontalLayout_14)
        self.t_label_comp3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp3.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp3.setFont(font)
        self.t_label_comp3.setObjectName(_fromUtf8("t_label_comp3"))
        self.formLayout_3.setWidget(10, QtGui.QFormLayout.LabelRole, self.t_label_comp3)
        self.t_label_rate3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate3.setObjectName(_fromUtf8("t_label_rate3"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.LabelRole, self.t_label_rate3)
        self.t_spin_rate3 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate3.setMaximum(999)
        self.t_spin_rate3.setProperty("value", 112)
        self.t_spin_rate3.setObjectName(_fromUtf8("t_spin_rate3"))
        self.formLayout_3.setWidget(11, QtGui.QFormLayout.FieldRole, self.t_spin_rate3)
        self.t_label_prot3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot3.setObjectName(_fromUtf8("t_label_prot3"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.LabelRole, self.t_label_prot3)
        self.t_spin_prot3 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot3.setProperty("value", 2)
        self.t_spin_prot3.setObjectName(_fromUtf8("t_spin_prot3"))
        self.formLayout_3.setWidget(12, QtGui.QFormLayout.FieldRole, self.t_spin_prot3)
        self.t_label_comp_src3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src3.setObjectName(_fromUtf8("t_label_comp_src3"))
        self.formLayout_3.setWidget(13, QtGui.QFormLayout.LabelRole, self.t_label_comp_src3)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.t_label_path_src3 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src3.sizePolicy().hasHeightForWidth())
        self.t_label_path_src3.setSizePolicy(sizePolicy)
        self.t_label_path_src3.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src3.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src3.setObjectName(_fromUtf8("t_label_path_src3"))
        self.horizontalLayout_15.addWidget(self.t_label_path_src3)
        self.t_btn_path_src3 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src3.setObjectName(_fromUtf8("t_btn_path_src3"))
        self.horizontalLayout_15.addWidget(self.t_btn_path_src3)
        self.formLayout_3.setLayout(13, QtGui.QFormLayout.FieldRole, self.horizontalLayout_15)
        self.t_label_comp4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp4.setFont(font)
        self.t_label_comp4.setObjectName(_fromUtf8("t_label_comp4"))
        self.formLayout_3.setWidget(14, QtGui.QFormLayout.LabelRole, self.t_label_comp4)
        self.t_label_rate4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate4.setObjectName(_fromUtf8("t_label_rate4"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.LabelRole, self.t_label_rate4)
        self.t_spin_rate4 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate4.setMaximum(999)
        self.t_spin_rate4.setProperty("value", 112)
        self.t_spin_rate4.setObjectName(_fromUtf8("t_spin_rate4"))
        self.formLayout_3.setWidget(15, QtGui.QFormLayout.FieldRole, self.t_spin_rate4)
        self.t_label_prot4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot4.setObjectName(_fromUtf8("t_label_prot4"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.LabelRole, self.t_label_prot4)
        self.t_spin_prot4 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot4.setProperty("value", 2)
        self.t_spin_prot4.setObjectName(_fromUtf8("t_spin_prot4"))
        self.formLayout_3.setWidget(16, QtGui.QFormLayout.FieldRole, self.t_spin_prot4)
        self.t_label_comp_src4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src4.setObjectName(_fromUtf8("t_label_comp_src4"))
        self.formLayout_3.setWidget(17, QtGui.QFormLayout.LabelRole, self.t_label_comp_src4)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.t_label_path_src4 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src4.sizePolicy().hasHeightForWidth())
        self.t_label_path_src4.setSizePolicy(sizePolicy)
        self.t_label_path_src4.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src4.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src4.setObjectName(_fromUtf8("t_label_path_src4"))
        self.horizontalLayout_16.addWidget(self.t_label_path_src4)
        self.t_btn_path_src4 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src4.setObjectName(_fromUtf8("t_btn_path_src4"))
        self.horizontalLayout_16.addWidget(self.t_btn_path_src4)
        self.formLayout_3.setLayout(17, QtGui.QFormLayout.FieldRole, self.horizontalLayout_16)
        self.t_label_comp5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp5.setFont(font)
        self.t_label_comp5.setObjectName(_fromUtf8("t_label_comp5"))
        self.formLayout_3.setWidget(18, QtGui.QFormLayout.LabelRole, self.t_label_comp5)
        self.t_label_rate5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate5.setObjectName(_fromUtf8("t_label_rate5"))
        self.formLayout_3.setWidget(19, QtGui.QFormLayout.LabelRole, self.t_label_rate5)
        self.t_spin_rate5 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate5.setMaximum(999)
        self.t_spin_rate5.setProperty("value", 112)
        self.t_spin_rate5.setObjectName(_fromUtf8("t_spin_rate5"))
        self.formLayout_3.setWidget(19, QtGui.QFormLayout.FieldRole, self.t_spin_rate5)
        self.t_label_prot5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot5.setObjectName(_fromUtf8("t_label_prot5"))
        self.formLayout_3.setWidget(20, QtGui.QFormLayout.LabelRole, self.t_label_prot5)
        self.t_spin_prot5 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot5.setProperty("value", 2)
        self.t_spin_prot5.setObjectName(_fromUtf8("t_spin_prot5"))
        self.formLayout_3.setWidget(20, QtGui.QFormLayout.FieldRole, self.t_spin_prot5)
        self.t_label_comp_src5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src5.setObjectName(_fromUtf8("t_label_comp_src5"))
        self.formLayout_3.setWidget(21, QtGui.QFormLayout.LabelRole, self.t_label_comp_src5)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.t_label_path_src5 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src5.sizePolicy().hasHeightForWidth())
        self.t_label_path_src5.setSizePolicy(sizePolicy)
        self.t_label_path_src5.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src5.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src5.setObjectName(_fromUtf8("t_label_path_src5"))
        self.horizontalLayout_17.addWidget(self.t_label_path_src5)
        self.t_btn_path_src5 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src5.setObjectName(_fromUtf8("t_btn_path_src5"))
        self.horizontalLayout_17.addWidget(self.t_btn_path_src5)
        self.formLayout_3.setLayout(21, QtGui.QFormLayout.FieldRole, self.horizontalLayout_17)
        self.t_label_comp6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp6.setFont(font)
        self.t_label_comp6.setObjectName(_fromUtf8("t_label_comp6"))
        self.formLayout_3.setWidget(22, QtGui.QFormLayout.LabelRole, self.t_label_comp6)
        self.t_label_rate6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate6.setObjectName(_fromUtf8("t_label_rate6"))
        self.formLayout_3.setWidget(23, QtGui.QFormLayout.LabelRole, self.t_label_rate6)
        self.t_spin_rate6 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate6.setMaximum(999)
        self.t_spin_rate6.setProperty("value", 112)
        self.t_spin_rate6.setObjectName(_fromUtf8("t_spin_rate6"))
        self.formLayout_3.setWidget(23, QtGui.QFormLayout.FieldRole, self.t_spin_rate6)
        self.t_label_prot6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot6.setObjectName(_fromUtf8("t_label_prot6"))
        self.formLayout_3.setWidget(24, QtGui.QFormLayout.LabelRole, self.t_label_prot6)
        self.t_spin_prot6 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot6.setProperty("value", 2)
        self.t_spin_prot6.setObjectName(_fromUtf8("t_spin_prot6"))
        self.formLayout_3.setWidget(24, QtGui.QFormLayout.FieldRole, self.t_spin_prot6)
        self.t_label_comp_src6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src6.setObjectName(_fromUtf8("t_label_comp_src6"))
        self.formLayout_3.setWidget(25, QtGui.QFormLayout.LabelRole, self.t_label_comp_src6)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.t_label_path_src6 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src6.sizePolicy().hasHeightForWidth())
        self.t_label_path_src6.setSizePolicy(sizePolicy)
        self.t_label_path_src6.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src6.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src6.setObjectName(_fromUtf8("t_label_path_src6"))
        self.horizontalLayout_18.addWidget(self.t_label_path_src6)
        self.t_btn_path_src6 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src6.setObjectName(_fromUtf8("t_btn_path_src6"))
        self.horizontalLayout_18.addWidget(self.t_btn_path_src6)
        self.formLayout_3.setLayout(25, QtGui.QFormLayout.FieldRole, self.horizontalLayout_18)
        self.t_label_comp7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.t_label_comp7.setFont(font)
        self.t_label_comp7.setObjectName(_fromUtf8("t_label_comp7"))
        self.formLayout_3.setWidget(26, QtGui.QFormLayout.LabelRole, self.t_label_comp7)
        self.t_label_rate7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_rate7.setObjectName(_fromUtf8("t_label_rate7"))
        self.formLayout_3.setWidget(27, QtGui.QFormLayout.LabelRole, self.t_label_rate7)
        self.t_spin_rate7 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_rate7.setMaximum(999)
        self.t_spin_rate7.setProperty("value", 112)
        self.t_spin_rate7.setObjectName(_fromUtf8("t_spin_rate7"))
        self.formLayout_3.setWidget(27, QtGui.QFormLayout.FieldRole, self.t_spin_rate7)
        self.t_label_prot7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_prot7.setObjectName(_fromUtf8("t_label_prot7"))
        self.formLayout_3.setWidget(28, QtGui.QFormLayout.LabelRole, self.t_label_prot7)
        self.t_spin_prot7 = QtGui.QSpinBox(self.scrollAreaWidgetContents)
        self.t_spin_prot7.setEnabled(True)
        self.t_spin_prot7.setProperty("value", 2)
        self.t_spin_prot7.setObjectName(_fromUtf8("t_spin_prot7"))
        self.formLayout_3.setWidget(28, QtGui.QFormLayout.FieldRole, self.t_spin_prot7)
        self.t_label_comp_src7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_comp_src7.setObjectName(_fromUtf8("t_label_comp_src7"))
        self.formLayout_3.setWidget(29, QtGui.QFormLayout.LabelRole, self.t_label_comp_src7)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.t_label_path_src7 = QtGui.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_label_path_src7.sizePolicy().hasHeightForWidth())
        self.t_label_path_src7.setSizePolicy(sizePolicy)
        self.t_label_path_src7.setMinimumSize(QtCore.QSize(100, 0))
        self.t_label_path_src7.setFrameShape(QtGui.QFrame.Box)
        self.t_label_path_src7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.t_label_path_src7.setObjectName(_fromUtf8("t_label_path_src7"))
        self.horizontalLayout_19.addWidget(self.t_label_path_src7)
        self.t_btn_path_src7 = QtGui.QToolButton(self.scrollAreaWidgetContents)
        self.t_btn_path_src7.setObjectName(_fromUtf8("t_btn_path_src7"))
        self.horizontalLayout_19.addWidget(self.t_btn_path_src7)
        self.formLayout_3.setLayout(29, QtGui.QFormLayout.FieldRole, self.horizontalLayout_19)
        self.verticalLayout_4.addLayout(self.formLayout_3)
        self.line_15 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.line_15.setFrameShape(QtGui.QFrame.HLine)
        self.line_15.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_15.setObjectName(_fromUtf8("line_15"))
        self.verticalLayout_4.addWidget(self.line_15)
        self.t_label_increase_num_subch_info = QtGui.QLabel(self.scrollAreaWidgetContents)
        self.t_label_increase_num_subch_info.setEnabled(False)
        font = QtGui.QFont()
        font.setItalic(True)
        font.setStrikeOut(False)
        self.t_label_increase_num_subch_info.setFont(font)
        self.t_label_increase_num_subch_info.setObjectName(_fromUtf8("t_label_increase_num_subch_info"))
        self.verticalLayout_4.addWidget(self.t_label_increase_num_subch_info)
        self.verticalLayout_9.addLayout(self.verticalLayout_4)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_5.addWidget(self.scrollArea)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.line_3 = QtGui.QFrame(self.tab_transmission)
        self.line_3.setFrameShape(QtGui.QFrame.VLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.horizontalLayout_7.addWidget(self.line_3)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.line_5 = QtGui.QFrame(self.tab_transmission)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.verticalLayout_8.addWidget(self.line_5)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_12 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.tab_transmission)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.t_edit_ensemble_label = QtGui.QLineEdit(self.tab_transmission)
        self.t_edit_ensemble_label.setObjectName(_fromUtf8("t_edit_ensemble_label"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.t_edit_ensemble_label)
        self.label_14 = QtGui.QLabel(self.tab_transmission)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.label_15 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.tab_transmission)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_16)
        self.t_edit_service_label = QtGui.QLineEdit(self.tab_transmission)
        self.t_edit_service_label.setObjectName(_fromUtf8("t_edit_service_label"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.t_edit_service_label)
        self.label_17 = QtGui.QLabel(self.tab_transmission)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_17)
        self.t_spin_num_subch = QtGui.QSpinBox(self.tab_transmission)
        self.t_spin_num_subch.setMaximum(7)
        self.t_spin_num_subch.setProperty("value", 1)
        self.t_spin_num_subch.setObjectName(_fromUtf8("t_spin_num_subch"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.FieldRole, self.t_spin_num_subch)
        self.label_23 = QtGui.QLabel(self.tab_transmission)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_23)
        self.t_combo_language = QtGui.QComboBox(self.tab_transmission)
        self.t_combo_language.setObjectName(_fromUtf8("t_combo_language"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.t_combo_language)
        self.t_combo_country = QtGui.QComboBox(self.tab_transmission)
        self.t_combo_country.setObjectName(_fromUtf8("t_combo_country"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.t_combo_country)
        self.line = QtGui.QFrame(self.tab_transmission)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.line)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_2.setItem(8, QtGui.QFormLayout.FieldRole, spacerItem7)
        self.verticalLayout_8.addLayout(self.formLayout_2)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.t_btn_init = QtGui.QPushButton(self.tab_transmission)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("network-transmit"))
        self.t_btn_init.setIcon(icon)
        self.t_btn_init.setObjectName(_fromUtf8("t_btn_init"))
        self.horizontalLayout_22.addWidget(self.t_btn_init)
        self.label_22 = QtGui.QLabel(self.tab_transmission)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_22.addWidget(self.label_22)
        self.t_label_status = QtGui.QLabel(self.tab_transmission)
        self.t_label_status.setObjectName(_fromUtf8("t_label_status"))
        self.horizontalLayout_22.addWidget(self.t_label_status)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_22)
        self.line_10 = QtGui.QFrame(self.tab_transmission)
        self.line_10.setFrameShape(QtGui.QFrame.HLine)
        self.line_10.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_10.setObjectName(_fromUtf8("line_10"))
        self.verticalLayout_8.addWidget(self.line_10)
        self.label_20 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_8.addWidget(self.label_20)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_18 = QtGui.QLabel(self.tab_transmission)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_20.addWidget(self.label_18)
        self.t_spin_listen_to_component = QtGui.QSpinBox(self.tab_transmission)
        self.t_spin_listen_to_component.setMinimum(1)
        self.t_spin_listen_to_component.setMaximum(1)
        self.t_spin_listen_to_component.setProperty("value", 1)
        self.t_spin_listen_to_component.setObjectName(_fromUtf8("t_spin_listen_to_component"))
        self.horizontalLayout_20.addWidget(self.t_spin_listen_to_component)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.t_btn_play = QtGui.QPushButton(self.tab_transmission)
        self.t_btn_play.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-start"))
        self.t_btn_play.setIcon(icon)
        self.t_btn_play.setObjectName(_fromUtf8("t_btn_play"))
        self.horizontalLayout_11.addWidget(self.t_btn_play)
        self.t_btn_stop = QtGui.QPushButton(self.tab_transmission)
        self.t_btn_stop.setEnabled(False)
        icon = QtGui.QIcon.fromTheme(_fromUtf8("media-playback-stop"))
        self.t_btn_stop.setIcon(icon)
        self.t_btn_stop.setObjectName(_fromUtf8("t_btn_stop"))
        self.horizontalLayout_11.addWidget(self.t_btn_stop)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_19 = QtGui.QLabel(self.tab_transmission)
        self.label_19.setEnabled(False)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_12.addWidget(self.label_19)
        self.t_slider_volume = QtGui.QSlider(self.tab_transmission)
        self.t_slider_volume.setEnabled(False)
        self.t_slider_volume.setMaximum(100)
        self.t_slider_volume.setProperty("value", 80)
        self.t_slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.t_slider_volume.setObjectName(_fromUtf8("t_slider_volume"))
        self.horizontalLayout_12.addWidget(self.t_slider_volume)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.mode_tabs.addTab(self.tab_transmission, _fromUtf8(""))
        self.verticalLayout.addWidget(self.mode_tabs)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setAutoFillBackground(False)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.mode_tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", None))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:20pt; font-weight:600;\">DABstep</span></p></body></html>", None))
        self.rbtn_USRP.setText(_translate("MainWindow", "USRP", None))
        self.label_frequency.setText(_translate("MainWindow", "Frequency", None))
        self.label_4.setText(_translate("MainWindow", "Hz ", None))
        self.rbtn_File.setText(_translate("MainWindow", "File", None))
        self.label_path.setText(_translate("MainWindow", "select path", None))
        self.btn_file_path.setText(_translate("MainWindow", "...", None))
        item = self.table_mci.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.table_mci.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Component", None))
        item = self.table_mci.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Mode", None))
        item = self.table_mci.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Type", None))
        self.label_ensemble.setText(_translate("MainWindow", "ENSEMBLE", None))
        self.label_26.setText(_translate("MainWindow", "services:", None))
        self.label_country.setText(_translate("MainWindow", "Country", None))
        self.label_snr.setText(_translate("MainWindow", "reception: ", None))
        self.label_7.setText(_translate("MainWindow", "dB", None))
        self.label_service.setText(_translate("MainWindow", "SERVICE", None))
        self.label_dabplus.setText(_translate("MainWindow", "DAB", None))
        self.label_bit_rate.setText(_translate("MainWindow", "bit rate", None))
        self.label_primary.setText(_translate("MainWindow", "primary", None))
        self.btn_init.setText(_translate("MainWindow", "set up receiver", None))
        self.btn_update_info.setText(_translate("MainWindow", "scan ensemble", None))
        self.label_2.setText(_translate("MainWindow", "Audio Player", None))
        self.btn_play.setText(_translate("MainWindow", "  Play", None))
        self.btn_stop.setText(_translate("MainWindow", "  Stop", None))
        self.btn_record.setText(_translate("MainWindow", "  Record", None))
        self.label_3.setText(_translate("MainWindow", "Volume", None))
        self.mode_tabs.setTabText(self.mode_tabs.indexOf(self.tab_reception), _translate("MainWindow", "Receiver", None))
        self.t_rbtn_USRP.setText(_translate("MainWindow", "USRP", None))
        self.t_label_frequency.setText(_translate("MainWindow", "Frequency", None))
        self.label.setText(_translate("MainWindow", "Hz ", None))
        self.t_rbtn_File.setText(_translate("MainWindow", "File", None))
        self.t_edit_file_name.setText(_translate("MainWindow", "gen_iq_dab.dat", None))
        self.t_label_sink.setText(_translate("MainWindow", "select path", None))
        self.t_btn_file_path.setText(_translate("MainWindow", "...", None))
        self.t_label_heading_service_comp.setText(_translate("MainWindow", "Service Components", None))
        self.t_label_comp1.setText(_translate("MainWindow", "Component 1", None))
        self.t_label_rate1.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot1.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src1.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src1.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src1.setText(_translate("MainWindow", "...", None))
        self.t_label_comp2.setText(_translate("MainWindow", "Component 2 ", None))
        self.t_label_rate2.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot2.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src2.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src2.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src2.setText(_translate("MainWindow", "...", None))
        self.t_label_comp3.setText(_translate("MainWindow", "Component 3", None))
        self.t_label_rate3.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot3.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src3.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src3.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src3.setText(_translate("MainWindow", "...", None))
        self.t_label_comp4.setText(_translate("MainWindow", "Component 4", None))
        self.t_label_rate4.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot4.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src4.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src4.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src4.setText(_translate("MainWindow", "...", None))
        self.t_label_comp5.setText(_translate("MainWindow", "Component 5", None))
        self.t_label_rate5.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot5.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src5.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src5.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src5.setText(_translate("MainWindow", "...", None))
        self.t_label_comp6.setText(_translate("MainWindow", "Component 6", None))
        self.t_label_rate6.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot6.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src6.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src6.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src6.setText(_translate("MainWindow", "...", None))
        self.t_label_comp7.setText(_translate("MainWindow", "Component 7", None))
        self.t_label_rate7.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.t_label_prot7.setText(_translate("MainWindow", "Protection Mode", None))
        self.t_label_comp_src7.setText(_translate("MainWindow", "Audio Source", None))
        self.t_label_path_src7.setText(_translate("MainWindow", "select audio", None))
        self.t_btn_path_src7.setText(_translate("MainWindow", "...", None))
        self.t_label_increase_num_subch_info.setText(_translate("MainWindow", "increase \"Number of channels\" for more components", None))
        self.label_12.setText(_translate("MainWindow", "Ensemble info", None))
        self.label_13.setText(_translate("MainWindow", "Label", None))
        self.t_edit_ensemble_label.setText(_translate("MainWindow", "Galaxy News", None))
        self.label_14.setText(_translate("MainWindow", "Country", None))
        self.label_15.setText(_translate("MainWindow", "Service", None))
        self.label_16.setText(_translate("MainWindow", "Label", None))
        self.t_edit_service_label.setText(_translate("MainWindow", "Wasteland Radio", None))
        self.label_17.setText(_translate("MainWindow", "Number of channels", None))
        self.label_23.setText(_translate("MainWindow", "Language", None))
        self.t_btn_init.setText(_translate("MainWindow", "  set up transmitter", None))
        self.label_22.setText(_translate("MainWindow", "Status:", None))
        self.t_label_status.setText(_translate("MainWindow", "not running", None))
        self.label_20.setText(_translate("MainWindow", "Audio Player", None))
        self.label_18.setText(_translate("MainWindow", "Listen to component", None))
        self.t_btn_play.setText(_translate("MainWindow", "  Play", None))
        self.t_btn_stop.setText(_translate("MainWindow", "  Stop", None))
        self.label_19.setText(_translate("MainWindow", "Volume", None))
        self.mode_tabs.setTabText(self.mode_tabs.indexOf(self.tab_transmission), _translate("MainWindow", "Transmitter", None))

