# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_frontend.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(655, 816)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_reception = QtGui.QWidget()
        self.tab_reception.setObjectName(_fromUtf8("tab_reception"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tab_reception)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        self.label_21 = QtGui.QLabel(self.tab_reception)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_6.addWidget(self.label_21)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbtn_USRP = QtGui.QRadioButton(self.tab_reception)
        self.rbtn_USRP.setChecked(True)
        self.rbtn_USRP.setAutoRepeat(False)
        self.rbtn_USRP.setObjectName(_fromUtf8("rbtn_USRP"))
        self.horizontalLayout.addWidget(self.rbtn_USRP)
        self.spinbox_frequency = QtGui.QSpinBox(self.tab_reception)
        self.spinbox_frequency.setMaximum(1000000000)
        self.spinbox_frequency.setProperty("value", 208064000)
        self.spinbox_frequency.setObjectName(_fromUtf8("spinbox_frequency"))
        self.horizontalLayout.addWidget(self.spinbox_frequency)
        self.label_frequency = QtGui.QLabel(self.tab_reception)
        self.label_frequency.setObjectName(_fromUtf8("label_frequency"))
        self.horizontalLayout.addWidget(self.label_frequency)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.rbtn_File = QtGui.QRadioButton(self.tab_reception)
        self.rbtn_File.setObjectName(_fromUtf8("rbtn_File"))
        self.horizontalLayout_6.addWidget(self.rbtn_File)
        self.label_path = QtGui.QLabel(self.tab_reception)
        self.label_path.setEnabled(False)
        self.label_path.setObjectName(_fromUtf8("label_path"))
        self.horizontalLayout_6.addWidget(self.label_path)
        self.btn_file_path = QtGui.QToolButton(self.tab_reception)
        self.btn_file_path.setEnabled(False)
        self.btn_file_path.setObjectName(_fromUtf8("btn_file_path"))
        self.horizontalLayout_6.addWidget(self.btn_file_path)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_6.addLayout(self.horizontalLayout_3)
        self.btn_init = QtGui.QPushButton(self.tab_reception)
        font = QtGui.QFont()
        font.setKerning(True)
        self.btn_init.setFont(font)
        self.btn_init.setCheckable(False)
        self.btn_init.setObjectName(_fromUtf8("btn_init"))
        self.verticalLayout_6.addWidget(self.btn_init)
        self.table_mci = QtGui.QTableWidget(self.tab_reception)
        self.table_mci.setObjectName(_fromUtf8("table_mci"))
        self.table_mci.setColumnCount(3)
        self.table_mci.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.table_mci.setHorizontalHeaderItem(2, item)
        self.verticalLayout_6.addWidget(self.table_mci)
        self.btn_update_info = QtGui.QPushButton(self.tab_reception)
        self.btn_update_info.setObjectName(_fromUtf8("btn_update_info"))
        self.verticalLayout_6.addWidget(self.btn_update_info)
        self.btn_debug = QtGui.QPushButton(self.tab_reception)
        self.btn_debug.setObjectName(_fromUtf8("btn_debug"))
        self.verticalLayout_6.addWidget(self.btn_debug)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.line = QtGui.QFrame(self.tab_reception)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_7.addWidget(self.line)
        self.txt_info = QtGui.QPlainTextEdit(self.tab_reception)
        self.txt_info.setObjectName(_fromUtf8("txt_info"))
        self.verticalLayout_7.addWidget(self.txt_info)
        self.label_2 = QtGui.QLabel(self.tab_reception)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Abyssinica SIL"))
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btn_play = QtGui.QPushButton(self.tab_reception)
        self.btn_play.setEnabled(False)
        self.btn_play.setObjectName(_fromUtf8("btn_play"))
        self.horizontalLayout_5.addWidget(self.btn_play)
        self.btn_stop = QtGui.QPushButton(self.tab_reception)
        self.btn_stop.setEnabled(False)
        self.btn_stop.setObjectName(_fromUtf8("btn_stop"))
        self.horizontalLayout_5.addWidget(self.btn_stop)
        self.btn_record = QtGui.QPushButton(self.tab_reception)
        self.btn_record.setEnabled(False)
        self.btn_record.setObjectName(_fromUtf8("btn_record"))
        self.horizontalLayout_5.addWidget(self.btn_record)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_3 = QtGui.QLabel(self.tab_reception)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.horizontalLayout_4.addWidget(self.label_3)
        self.slider_volume = QtGui.QSlider(self.tab_reception)
        self.slider_volume.setEnabled(False)
        self.slider_volume.setMaximum(100)
        self.slider_volume.setProperty("value", 80)
        self.slider_volume.setSliderPosition(80)
        self.slider_volume.setOrientation(QtCore.Qt.Horizontal)
        self.slider_volume.setObjectName(_fromUtf8("slider_volume"))
        self.horizontalLayout_4.addWidget(self.slider_volume)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_7)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.tabWidget.addTab(self.tab_reception, _fromUtf8(""))
        self.tab_transmission = QtGui.QWidget()
        self.tab_transmission.setObjectName(_fromUtf8("tab_transmission"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_transmission)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_22 = QtGui.QLabel(self.tab_transmission)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.verticalLayout_5.addWidget(self.label_22)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.radioButton = QtGui.QRadioButton(self.tab_transmission)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.horizontalLayout_9.addWidget(self.radioButton)
        self.spinbox_frequency_2 = QtGui.QSpinBox(self.tab_transmission)
        self.spinbox_frequency_2.setMaximum(1000000000)
        self.spinbox_frequency_2.setProperty("value", 208064000)
        self.spinbox_frequency_2.setObjectName(_fromUtf8("spinbox_frequency_2"))
        self.horizontalLayout_9.addWidget(self.spinbox_frequency_2)
        self.label_frequency_2 = QtGui.QLabel(self.tab_transmission)
        self.label_frequency_2.setObjectName(_fromUtf8("label_frequency_2"))
        self.horizontalLayout_9.addWidget(self.label_frequency_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.radioButton_2 = QtGui.QRadioButton(self.tab_transmission)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.horizontalLayout_10.addWidget(self.radioButton_2)
        self.label_23 = QtGui.QLabel(self.tab_transmission)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_10.addWidget(self.label_23)
        self.toolButton = QtGui.QToolButton(self.tab_transmission)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_10.addWidget(self.toolButton)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_12 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_12)
        self.label_13 = QtGui.QLabel(self.tab_transmission)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_13)
        self.lineEdit_3 = QtGui.QLineEdit(self.tab_transmission)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_14 = QtGui.QLabel(self.tab_transmission)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_14)
        self.lineEdit_5 = QtGui.QLineEdit(self.tab_transmission)
        self.lineEdit_5.setObjectName(_fromUtf8("lineEdit_5"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_5)
        self.label_15 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_15)
        self.label_16 = QtGui.QLabel(self.tab_transmission)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_16)
        self.lineEdit_6 = QtGui.QLineEdit(self.tab_transmission)
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_6)
        self.label_17 = QtGui.QLabel(self.tab_transmission)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_17)
        self.spinBox_5 = QtGui.QSpinBox(self.tab_transmission)
        self.spinBox_5.setObjectName(_fromUtf8("spinBox_5"))
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.FieldRole, self.spinBox_5)
        self.label_18 = QtGui.QLabel(self.tab_transmission)
        font = QtGui.QFont()
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.formLayout_2.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_18)
        self.label_19 = QtGui.QLabel(self.tab_transmission)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_19)
        self.spinBox_6 = QtGui.QSpinBox(self.tab_transmission)
        self.spinBox_6.setObjectName(_fromUtf8("spinBox_6"))
        self.formLayout_2.setWidget(7, QtGui.QFormLayout.FieldRole, self.spinBox_6)
        self.label_20 = QtGui.QLabel(self.tab_transmission)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_20)
        self.spinBox_7 = QtGui.QSpinBox(self.tab_transmission)
        self.spinBox_7.setObjectName(_fromUtf8("spinBox_7"))
        self.formLayout_2.setWidget(8, QtGui.QFormLayout.FieldRole, self.spinBox_7)
        self.verticalLayout_5.addLayout(self.formLayout_2)
        self.horizontalLayout_7.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7.addLayout(self.verticalLayout_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.tabWidget.addTab(self.tab_transmission, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.Heading = QtGui.QLabel(self.centralwidget)
        self.Heading.setObjectName(_fromUtf8("Heading"))
        self.verticalLayout.addWidget(self.Heading)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label_21.setText(_translate("MainWindow", "Source", None))
        self.rbtn_USRP.setText(_translate("MainWindow", "USRP", None))
        self.label_frequency.setText(_translate("MainWindow", "frequency", None))
        self.rbtn_File.setText(_translate("MainWindow", "File", None))
        self.label_path.setText(_translate("MainWindow", "select path", None))
        self.btn_file_path.setText(_translate("MainWindow", "...", None))
        self.btn_init.setText(_translate("MainWindow", "init", None))
        item = self.table_mci.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID", None))
        item = self.table_mci.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Reference", None))
        item = self.table_mci.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Type", None))
        self.btn_update_info.setText(_translate("MainWindow", "update", None))
        self.btn_debug.setText(_translate("MainWindow", "DEBUG", None))
        self.label_2.setText(_translate("MainWindow", "Audio Player", None))
        self.btn_play.setText(_translate("MainWindow", "Play", None))
        self.btn_stop.setText(_translate("MainWindow", "Stop", None))
        self.btn_record.setText(_translate("MainWindow", "Record", None))
        self.label_3.setText(_translate("MainWindow", "Volume", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_reception), _translate("MainWindow", "Receiver", None))
        self.label_22.setText(_translate("MainWindow", "Sink", None))
        self.radioButton.setText(_translate("MainWindow", "USRP", None))
        self.label_frequency_2.setText(_translate("MainWindow", "frequency", None))
        self.radioButton_2.setText(_translate("MainWindow", "RadioButton", None))
        self.label_23.setText(_translate("MainWindow", "select path", None))
        self.toolButton.setText(_translate("MainWindow", "...", None))
        self.label_12.setText(_translate("MainWindow", "Ensemble info", None))
        self.label_13.setText(_translate("MainWindow", "Label", None))
        self.label_14.setText(_translate("MainWindow", "Country ID", None))
        self.label_15.setText(_translate("MainWindow", "Service", None))
        self.label_16.setText(_translate("MainWindow", "Label", None))
        self.label_17.setText(_translate("MainWindow", "Number of channels", None))
        self.label_18.setText(_translate("MainWindow", "Component 1", None))
        self.label_19.setText(_translate("MainWindow", "Data rate [kbit/s]", None))
        self.label_20.setText(_translate("MainWindow", "Protection Mode", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_transmission), _translate("MainWindow", "Transmitter", None))
        self.Heading.setText(_translate("MainWindow", "DABstep", None))

